---
inventory:
    plugin: SimpleInventory
    options:
        host_file: "/home/alinbandiu/Documents/Proiect_Licenta_Bandiu_Alin_442D/hosts.yaml"
        group_file: "/home/alinbandiu/Documents/Proiect_Licenta_Bandiu_Alin_442D/groups.yaml"
        defaults_file: "/home/alinbandiu/Documents/Proiect_Licenta_Bandiu_Alin_442D/defaults.yaml"

runner:
  plugin: threaded
  options:
    num_workers: 100